### ISSUE TITLE
Reboot on Resume From Suspend - Full Rom Bay Trail

### ISSUE THREAD

**Issue by natloh** [MrChromebox/firmware#38] opened 2017-01-05 17:31 UTC
When using the full rom on a bay trail device, resuming from suspend results in a hard reboot.
Best workaround I have found is to disable suspend all together and so you shutting off the screen when the lid is closed. Not ideal, but it helps conserve a little battery.

**Comment by ReddestDream** [comment] 2017-01-05 17:55
We are aware of this issue and working on finding the cause.

**Comment by ReddestDream** [comment] 2017-01-19 17:18
I believe I have found a solution to this issue. The SPI write-protect range is not being properly cleared upon flashing on Atom. It was cleared properly on SNB/IVB/HSW/BDW, but it is not being cleared properly on Atom devices (BYT/BSW). This is breaking writing the MRC cache in custom firmwares, causing memory failures that break suspend. This should be fixable by specifically clearing the write protect range before flashing (flashrom --wp-range 0 0).

**Comment by ReddestDream** [comment] 2017-01-24 16:21
This is now fixed in the 01/23 UEFI Bay Trail ROM.

Should be closed. Thx.

**Closed as completed** 2017-01-24 16:31 UTC
