### ISSUE TITLE
Asus CN60 can't enroll in management

### ISSUE THREAD

**Issue by getut** [MrChromebox/firmware#426] opened 2023-01-31 20:41 UTC
I have a CN60 that I am testing to breath life into a bunch more if I can get them to work. I have successfully installed the mrchromebox uefi full rom and then also successfully installed chromeos flex. On first boot I tried to enroll and I got the error message about installation-time attributes lock. I went googling again and found that the TPM had to be cleared, so found instructions and downloaded galliumOS for haswell, booted from that, installed tpm-tools while booted in the live cd, and then ran sudo tpm_clear -f. It said it cleared, so I rebooted when it requested. On the next boot to chromeOS flex, it now said it detected a TPM module and asked me to reboot again. I did, and on next reboot it seemed to boot normally, but I then tried to enroll again and got exactly the same error that I started with. I don't know where to go from here. OH.. it is showing the device in my google management interface but it lists nothing about model and versions.

**Comment by MrChromebox** [comment] 2023-01-31 22:39
I'm honestly not sure what the issue is, other than something related to the TPM, which is not fully functional yet in the UEFI firmware

**Comment by Straunge** [comment] 2023-03-01 19:13
Just writing here to add onto this; I have flashed Flex with full UEFI to a Lenovo N21, N23, and a Dell 11 3180.  All of which work perfectly fine as an individual user.  Fingers crossed we get TPM integration in the UEFI.

**Comment by MrChromebox** [comment] 2023-04-30 02:20
TPM 1.2 admin will be included in the 4.20 release. Tested working across all pre-Skylake Chromebooks

**Comment by XBGT351** [comment] 2023-05-08 15:47
When is 4.20 release scheduled to be released ?

**Comment by MrChromebox** [comment] 2023-05-08 16:20
after coreboot 4.20 is released. it was supposed to be released on 4/20/2023, but has been delayed a few weeks

**Comment by MrChromebox** [comment] 2023-05-17 14:42
Fixed in MrChromebox-4.20.0 firmware release

**Closed as completed by MrChromebox** 2023-05-17 14:42 UTC
