### ISSUE TITLE
Cant boot any OS

### ISSUE THREAD

**Issue by Mrnermaler** [MrChromebox/firmware#572] opened 2024-01-23 00:06 UTC
I keep getting failed verify its a contains a 64bit UEFI OS but i know it's 64 bit UEFI os because it worked before

**Comment by MrChromebox** [comment] 2024-01-23 01:56
ok? You can't provide a half-assed error description and expect anyone to be able to help. Some basic info would be nice, such as:

* device you're using
* firmware version from UEFI menu
* exact steps you're taking
* full and exact error message (pic is fine)

**Comment by micmalti** [comment] 2024-02-06 01:40
OP probably ran some Linux distro from a USB which, upon installation, failed to boot up from the internal drive (hence the phrase "because it worked before"):

![PXL_20240206_012222332](https://github.com/MrChromebox/firmware/assets/31540652/3acd67a5-ffd2-47b2-9f3a-60b00bc5c139)

I'm met with the same problem on my Chromebook Plus 515 (CB515-2H-31NY) with board name `OMNIGUL`. Tried multiple distros (Ubuntu 23.10, EndeavourOS, Manjaro) with and without using Ventoy, but the outcome was the same regardless: the EFI partition showed up in the boot menu (path: `\EFI\[distro name]\grubx64.efi`) but it produced the above error message when selected, followed by this message in the UEFI shell:
`map: No mapping found`

I would also like to add that there weren't any installation errors, and can confirm that the EFI and root partitions were visible and accessible from the live USB session.

Here's the cbmem logs: [cbmem.log](https://github.com/MrChromebox/firmware/files/14173621/cbmem.log)

**Comment by MrChromebox** [comment] 2024-02-06 02:49
@micmalti boot to the UEFI boot menu. If there's no entry present for the internal storage, then that's your problem -- edk2 doesn't recognize it, and so the 'Manjaro' boot entry points to a device/path that doesn't exist.

**Comment by micmalti** [comment] 2024-02-06 03:02
You mean checking for entries in Boot Manager → Boot From File, as it says in the FAQ? It's empty. I'm not sure how I can add the entry manually.

**Comment by MrChromebox** [comment] 2024-02-06 15:08
no, literally press ESC then select Boot Menu. It should list the UEFI shell, the internal storage, and any boot entries added by the OS (eg, 'Manjaro')

**Comment by micmalti** [comment] 2024-02-06 15:11
Yes, there's an entry but it produces the same error message when selected.

**Comment by micmalti** [comment] 2024-02-06 15:21
Shall I consider using efibootmgr as suggested [here](https://superuser.com/questions/1768696/re-adding-efi-file-to-uefi-boot)?

**Comment by MrChromebox** [comment] 2024-02-06 16:03
no. post a pic of your boot menu, as well as the Boot From File options

**Comment by micmalti** [comment] 2024-02-06 16:15
Please note that only one distro is visible in the boot menu since I had previously removed the others:

![PXL_20240206_161135424](https://github.com/MrChromebox/firmware/assets/31540652/f5531de5-b3a0-484d-9eae-c4b622720d42)

![PXL_20240206_161206401](https://github.com/MrChromebox/firmware/assets/31540652/d3a62ed5-0e63-49fe-ad44-8994423d4be4)

**Comment by MrChromebox** [comment] 2024-02-06 16:21
it's exactly as I said before:

> If there's no entry present for the internal storage, then that's your problem -- edk2 doesn't recognize it, and so the 'Manjaro' boot entry points to a device/path that doesn't exist.

your internal storage is not recognized by edk2, so it's not bootable.

**Comment by micmalti** [comment] 2024-02-06 16:31
Is there a way that I can specify the path manually without using efibootmgr? My understanding is that the solution in the FAQ only works if the EFI partition is already visible in the File Explorer.

**Comment by MrChromebox** [comment] 2024-02-06 16:34
there is no workaround, other than booting from removable media. 

The Manjaro entry already specifies a path -- that path doesn't exist because your internal storage doesn't exist.

edk2 needs to be updated/fixed to support UFS boot media

**Comment by micmalti** [comment] 2024-02-06 16:38
Then it seems I have to revert back, unless there's a fix in the near future. Too bad.

**Comment by MrChromebox** [comment] 2024-02-06 16:38
do you have a SuzyQ cable? that would help in debugging

**Comment by micmalti** [comment] 2024-02-06 16:42
No, but I'll try to find one. I've seen a tutorial on how to make one but I'm not sure that I can do it.

**Comment by micmalti** [comment] 2024-02-06 17:00
I think that in the meantime, it's a good idea to specify in the docs that devices with UFS media are currently unsupported.

**Comment by MrChromebox** [comment] 2024-02-06 18:18
I think the UFS drivers were simply not being compiled into edk2, ping me on Discord for a test build with them enabled

**Comment by micmalti** [comment] 2024-02-06 18:22
Where can I obtain an invite?

**Comment by MrChromebox** [comment] 2024-02-06 18:23
https://discord.gg/j5YjPWp9

**Comment by ghost** [comment] 2024-02-16 13:04
My Acer 515 chromebook arrived yesterday, and this issue also affects me. Any idea when the test build will be released?

Thank you.

**Comment by MrChromebox** [comment] 2024-02-16 14:07
there will be no test build released, the solution I tried did not work. Need to get my hands one for testing

**Comment by ghost** [comment] 2024-02-16 14:12
Thank you for the quick reply. Apart from the HD not being detected, I like the machine. For now, I can boot off another USB. Keep up the great work, by the way. I've had Linux running on my older Acer for years.

**Comment by ghost** [comment] 2024-02-17 14:15
I'd be happy to test any builds, if that would help? My intention is never to use the CB as a CB anyway, so I'm not at any loss to rinse and repeat. 

Let me know.

**Comment by mdrobnak** [comment] 2024-04-15 22:37
Is the current workaround to boot off USB, but then the rootfs can still be on a UFS device? Since I had issues with a different device, I have one of these (CB515-2H) on order, because I thought it was supported and inexpensive...and now see this bug. :)

I can certainly deal with the USB workaround for now, and would definitely be up to helping test / attempt to contribute as well. I have another Linux laptop and server that I can set up a dev environment if pointed to some docs.

-Matt

**Comment by MrChromebox** [comment] 2024-04-16 00:54
I've got a fix for UFS-equipped devices, just need to push updates - will try to do so later tonight/tomorrow morning

**Comment by micmalti** [comment] 2024-04-16 01:18
Booting directly from UFS is currently possible, but you need to manually install the missing UFS modules. Something that I've yet to solve is the boot time which takes about 2min (probably a non-critical module that's failing to load). I'll try to test the update and check whether it addresses this issue as well.

**Comment by mdrobnak** [comment] 2024-04-16 01:29
> I've got a fix for UFS-equipped devices, just need to push updates - will try to do so later tonight/tomorrow morning

Awesome! Thanks for all your work.

-Matt

**Comment by ghost** [comment] 2024-04-16 02:25
This is super news! Maybe now I can make use of my Acer Plus Chromebook!  Thank you SO MUCH for your work.

-Keith

**Comment by MrChromebox** [comment] 2024-04-16 14:01
updated 4.22.4 ROMs pushed for all ADL/ADL-N boards

**Comment by ghost** [comment] 2024-04-17 11:26
Hi. I might be doing something wrong, but I updated the firmware to the latest version, and tried to install OpenSuSE and Void Linux, but neither see the UFS disk.

When you say "Booting directly from UFS is currently possible, but you need to manually install the missing UFS modules"...how does one go about that, or is it not related to my issue?

Thank you very much.

-K

**Comment by micmalti** [comment] 2024-04-17 12:31
Just tested Manjaro and Ubuntu 23.10 and both failed to boot out of the box.

**Comment by micmalti** [comment] 2024-04-17 12:43
@karmst, the instructions vary between different distros. The missing module is `ufshcd-pci`.

Edit: After a quick search, it seems that both OpenSUSE and Void Linux use dracut to regenerate the initramfs, which means you can do the following in chroot to add the missing module ([source](https://discovery.endeavouros.com/installation/dracut/2022/12/)):
`echo 'add_dracutmodules+=" ufshcd-pci "' >> /etc/dracut.conf.d`
`sudo dracut-rebuild`

**Comment by ghost** [comment] 2024-04-17 14:48
@micmalti, thank you for the invaluable information. But, I cannot even get the installer to see the UFS disk. When the installer starts, off a VENTOY disk with ISOs, the disk in the chromebook is not seen. So, I can't even partition the disk to get the OS installed.

Any ideas?

Thank you very much.

**Comment by MrChromebox** [comment] 2024-04-17 15:50
@karmst are you running the latest 4.22.4 firmware (2024/04/16) ? that is mandatory for UFS support

**Comment by ghost** [comment] 2024-04-17 16:21
> @karmst are you running the latest 4.22.4 firmware (2024/04/16) ? that is mandatory for UFS support

Yes, I am. I updated it last night.

**Comment by MrChromebox** [comment] 2024-04-17 16:33
> > @karmst are you running the latest 4.22.4 firmware (2024/04/16) ? that is mandatory for UFS support
> 
> Yes, I am. I updated it last night.

on what device? the UFS storage is not showing under the UEFI boot menu?

**Comment by ghost** [comment] 2024-04-17 16:44
> > > @karmst are you running the latest 4.22.4 firmware (2024/04/16) ? that is mandatory for UFS support
> > 
> > 
> > Yes, I am. I updated it last night.
> 
> on what device? the UFS storage is not showing under the UEFI boot menu?

It's an Acer 515 plus. There is nothing showing in the UEFI boot menu. Ubuntu did see the disk, but then did not boot after install. Void sees the disk for installation, and reports it as 953GB. I can partition it, but then it only recognizes 1 partition, and not the 6 I put on there. If I could get Ubuntu installed, that would be OK.

Weird that the disk does not show up as something in the UEFI menu.

**Comment by MrChromebox** [comment] 2024-04-17 16:48
> Acer 515 plus

board name?

**Comment by micmalti** [comment] 2024-04-17 16:57
You should be able to install Ubuntu 23.10 without any issues. However to boot it, you need to pass a different set of commands in chroot:
`echo "ufshcd" >> /etc/initramfs-tools/modules` 
`echo "ufshcd-pci" >> /etc/initramfs-tools/modules`

Edit: I followed my own instructions but without including `ufshcd` and it still worked.

**Comment by ghost** [comment] 2024-04-17 17:24
I will try ubuntu again after lunch, and boot off the ISO again and redo the grub stuff.

Thanks a million, once again!

-Keith

**Comment by MrChromebox** [comment] 2024-04-17 17:27
> I will try ubuntu again after lunch, and boot off the ISO again and redo the grub stuff.
> 
> Thanks a million, once again!
> 
> -Keith

FFS, none of that will make a difference if the boot device isn't visible in the UEFI boot menu.

WHAT IS THE DEVICE BOARD NAME

**Comment by ghost** [comment] 2024-04-17 18:03
The platform is Intel AlderLake / RaptorLake-U/P.

**Comment by micmalti** [comment] 2024-04-17 18:09
> The platform is Intel AlderLake / RaptorLake-U/P.

Boot with a USB, run MrChromebox's firmware script, and report the BOARD NAME.

**Comment by ghost** [comment] 2024-04-17 18:10
> > The platform is Intel AlderLake / RaptorLake-U/P.
> 
> Boot with a USB, run MrChromebox's firmware script, and report the BOARD NAME.

I just did. Sorry for the delay. The platform is Intel AlderLake / RaptorLake-U/P.

**Comment by micmalti** [comment] 2024-04-17 18:12
That's not the board name. Could you send the terminal info? If you're seeing `OMNIGUL`, then your device should work. We can't help you unless we're sure what device are we dealing with.

**Comment by ghost** [comment] 2024-04-17 18:16
Here's all the info from the script:

Acer Chromebook Plus 515 [CB515-2H] (OMNIGUL-FUQB)

Then it mentions the platform and then FW Type and version.

**Comment by ghost** [comment] 2024-04-17 18:21
I'll try and get you the information, really I will, but nowhere do I see board name. I run the firmware-util.sh script. Is there something else I can run to get the information?

**Comment by micmalti** [comment] 2024-04-17 18:23
It's `OMNIGUL-FUQB`. You did well :grinning:

**Comment by MrChromebox** [comment] 2024-04-17 18:23
the board name is shown at the top/center of the UEFI settings page, after the device's manufacturer/name, in parentheses. It's also shown in the header of the Firmware Util script, again in parentheses after the device manufacturer/marketing name

**Comment by MrChromebox** [comment] 2024-04-17 18:24
the 4.22.4 release has full support for UFS, so if it's not being listed in the UEFI boot menu, then something else is going on. There is nothing to be done or no workaround from the OS side, it's a firmware issue

**Comment by ghost** [comment] 2024-04-17 18:26
How do I find the point release of the firmware script?  I do see I'm running 2024-04-16, so I would assume it's the latest as I just curled the script following the instructions.

I want to rule out me doing something stupid :)

**Comment by micmalti** [comment] 2024-04-17 18:27
@MrChromebox, @karmst said the model is shown as `OMNIGUL`. I don't see why it can't be bootable if mine has the same board.

**Comment by ghost** [comment] 2024-04-17 18:30
> @MrChromebox, @karmst said the model is shown as `OMNIGUL`. I don't see why it can't be bootable if mine has the same board.

Mine shows nothing in the UEFI boot menu. Nada.

**Comment by mdrobnak** [comment] 2024-04-17 18:35
Stupid question but have you attempted to install an OS yet? You should be able to boot off USB no matter what..
Usually the boot menu will show only items which _are eligible for boot_ ie valid boot sources.

**Comment by ghost** [comment] 2024-04-17 18:38
Yes. I installed Lubuntu 22.04 (not my favourite OS, but just as a test).
Then I did the additional step of adding in the modules and rebuilding the init stuff.
But, I'm out of luck if the UEFI boot menu shows me nothing.

**Comment by MrChromebox** [comment] 2024-04-17 18:40
> Usually the boot menu will show only items which are eligible for boot ie valid boot sources.

no, the internal device will always be listed even if it's not bootable (unless it's not detected in this case, or has manually been removed from the boot device list)

> But, I'm out of luck if the UEFI boot menu shows me nothing.

it means we need to debug further. Do you have a SuzyQ cable?

**Comment by micmalti** [comment] 2024-04-17 18:41
> the 4.22.4 release has full support for UFS, so if it's not being listed in the UEFI boot menu, then something else is going on. There is nothing to be done or no workaround from the OS side, it's a firmware issue

As things stand, at least for the Linux distros that I've tested, one still has to manually add the `ufshcd-pci` module to have a bootable system. I was hopeful that the latest update was going to fix this, but it didn't (an OS issue, I presume). Yet, I'm still grateful for the fact that the hanging boot issue that I was previously experiencing has gone away, so thank you.

**Comment by MrChromebox** [comment] 2024-04-17 18:41
> How do I find the point release of the firmware script?

the script doesn't have a version. You can check your fw version on the main page of the UEFI settings, just like with the board name. it literally says, Fw version: xxxxx

**Comment by mdrobnak** [comment] 2024-04-17 18:42
> > Usually the boot menu will show only items which are eligible for boot ie valid boot sources.
> 
> no, the internal device will always be listed even if it's not bootable (unless it's not detected in this case, or has manually been removed from the boot device list)

I stand corrected!

**Comment by ghost** [comment] 2024-04-17 18:44
MMmm...on the UEFI main page, it says the FW is Google OMNIGUL. It that OK, or does that actually mean the FW was not updated?

What should one see on the UEFI page when the FW is updated, as in via the script?

**Comment by micmalti** [comment] 2024-04-17 18:45
@karmst can you send a screenshot of the UEFI boot menu once you've installed Lubuntu?

**Comment by ghost** [comment] 2024-04-17 18:49
![PXL_20240417_144644224](https://github.com/MrChromebox/firmware/assets/1964634/6e1844b8-1855-43e4-b33f-9f7c2a25edce)
![PXL_20240417_144701530](https://github.com/MrChromebox/firmware/assets/1964634/e77b2e38-c64e-4dd2-b380-fe8ab82590bc)

**Comment by MrChromebox** [comment] 2024-04-17 18:51
[facepalm] you're using RW_LEGACY firmware

**Comment by ghost** [comment] 2024-04-17 18:55
By your response, I guess I did something wrong ;)
Wait, does that mean if I do the NIX install the legacy boot way, it will work?

**Comment by MrChromebox** [comment] 2024-04-17 19:11
absolutely not -- it means that we were assuming you were running the UEFI Full ROM firmware, like everyone else in this thread.

I just now updated the RW_LEGACY firmware to add UFS support. 

That said, RWL is for dual booting ChromeOS and Linux, not replacing ChromeOS with Linux, because there are things that will not work, and nothing I can do about them *since you are still running the stock firmware*. 

If you're going to wipe ChromeOS and run Linux, you need to use the UEFI Full ROM firmware.

**Comment by ghost** [comment] 2024-04-17 19:16
Sorry for the trouble. I should have stated what version of the FW I was running. I didn't want to do the full UEFI, as I don't have the tools to disable the r/w setting and all that. RW/LEGACY is just easier for me. And it's the way I've been running linux in the past...so I went with what I know.

Again, my apologies for the confusion I caused. Let me look in to how I can maybe get the full UEFI FW installed.

Cheers,

-K

**Comment by MrChromebox** [comment] 2024-04-17 19:20
at the very least, please update the RW_LEGACY firmware now and see if the UFS internal storage is now listed in the boot menu

**Comment by ghost** [comment] 2024-04-17 19:23
OK, I will do that this evening and report back. I am sure it will work. The work you do for us is amazing.

Thanks again!

**Comment by ghost** [comment] 2024-04-18 17:59
An update. I upgraded the RW/LEGACY FW and the UFS drive now shows up in the boot menu. I was able to install lubuntu, and it boots well after I redid the init. ubuntu, openSuSE, void will not boot. Says something about no 64-bit OS installed.

openSuSE does not even see the UFS Drive in the installer, whereas the other flavours do (even though Void reports it as 953GB rather than 128GB). Any way, I got one flavour of Ubuntu installed and working.

That is OK. I can live with lubuntu. No sound, but I can figure that out hopefully.

Thanks again for all your help.

**Comment by micmalti** [comment] 2024-04-18 18:53
FWIW, you may install EndeavourOS or another Arch-based distro and have working Bluetooth and USB sound using the audio script linked in the docs.

**Closed as completed** 2024-04-18 18:54 UTC

**Comment by ghost** [comment] 2024-04-18 19:03
> FWIW, you may install EndeavourOS or another Arch-based distro and have working Bluetooth and USB sound using the audio script linked in the docs.

Funny you should say that, because I just blew away lubuntu and installed Manjaro. I had to add a couple of ufs modules and mkinitcpio. Works like a champ. So, I'll dig out the script and take a shot at it.

Thanks again!

**Comment by micmalti** [comment] 2024-04-18 20:40
@karmst join the Discord server so we can move this conversation further.

**Comment by micmalti** [comment] 2024-06-10 12:02
@karmst did you have any luck with resolving the audio issues in Manjaro? Kindly respond [here](https://forum.chrultrabook.com/t/audio-issues-running-manjaro-with-pulseaudio-on-omnigul/1744) with your workarounds/suggestions.

**Comment by Rosmer168** [comment] 2024-07-20 06:46
Hello, good evening. I currently have a Chromebook with the UEFI ROM. The code name of the Chrome is the Wolf. The ROM currently installed is version 4.22.4. What system could I currently install on said Chromebook? I tested it with Windows 10 and Windows 11. I wanted to use Windows. 8.1 but the touchpad drivers were not compatible, of course I have not yet tested with any Linux distro and I don't know if I should try it because of what I read they still do not solve the implementation of the Linux boot in said UEFI boot

**Comment by MrChromebox** [comment] 2024-07-20 12:32
@Rosmer168 this issue is closed and your question does not appear related. WOLF has been working fully with all OS for 5+ years now. There is no UEFI boot issue? I don't know what you are reading, but mrchromebox.tech is the authoritative source for ChromeOS device firmware, and docs.chrultrabook.com is the authoritative source for OS compatibility.

**Comment by PD-Kerman** [comment] 2024-08-18 11:23
> > FWIW, you may install EndeavourOS or another Arch-based distro and have working Bluetooth and USB sound using the audio script linked in the docs.
> 
> Funny you should say that, because I just blew away lubuntu and installed Manjaro. I had to add a couple of ufs modules and mkinitcpio. Works like a champ. So, I'll dig out the script and take a shot at it.
> 
> Thanks again!

Hi there
I just got a elemi / hp c640 g2 here and seems like the issue still remains on this model, which it doesnt seem like i could boot the system from the microsd card in the slot~ 

ill first paste the brief post on discord (chrultraboook) but unfortunately there r no support on the discord server~
![QQ_1723978137283](https://github.com/user-attachments/assets/7f97b744-9ebf-4508-854a-543c49ffbed3)

# So after reading all previous comments/discussions under this thread, i guess ill just firstly post these infos cuz they should be related most: 

-  **FW_VER: Okey so firstly, i just ran the installation script today, and the date of the firmware seems to be 06/15/2024 as its been shown here** 

![b4cba7a546945f70918a0c5d28282cfd_720](https://github.com/user-attachments/assets/47b7f676-46e0-4a09-9c05-fa89bade6fcd)

- **BOOTMENU: And according to the previous discussion i noticed that i the device should still being displayed in the boot menu regardless of whether its bootable so the following attachment show that the microsd card was nicely plugged in and i can confirm that it was recognized in all installation media and its been tested usable**
![08e5245608eec1c74da6994fa2cd5017_720](https://github.com/user-attachments/assets/714297d1-5d43-4a82-9159-3697a06d29b0)

![dfcd588cddbd3429b2dbea889baff3c9_720](https://github.com/user-attachments/assets/b2d18468-6002-4fb6-a7ea-c4dc0dd08e81)

- **MISCELLANEOUS: Here's some additional screenshots about the blank file explorer and the UEFI Shell with `map: No mapping found.` notice which seems like no devices were even detected even tho the microsdcard had been inserted**



# What i did: 

**Well i was originally wanted to install the entire operating system on the microsd card in the built in slot cuz the slot could get it locked inside which should be save enough and my internal storage was like i only got 64GB which wasnt enought and speaking of which _the internal eMMC didnt displayed on the firmware as well_

and i _tried both ubuntu and arch linux and the USB installation media works both perfectectly fine_, and ive attempted to install it to both eMMC and microsd card separately _both didnt boot_ (*might need to get internal eMMC one tested again to confirm)

_which means yea even tho the microsdcard is bootable/freshly installed, it is still not detectable_

and about the microsd card its a sandisk extreme 256GB and again works perfectly fine ive been tested it for several times~
**

its kind of a really important feature and i really wish it could be fixed
please let me know if any other infos were required :D

All kinds of help at all would be very much appreciated!~ 
Thanks in advance
