### ISSUE TITLE
Acer Chromebook C738t USB option to boot wint show in Mr Chromebox's Boot menu! [image](https://github.com/MrChromebox/firmware/assets/136679962/8b240330-db2b-44df-ade9-96af74f60c8a)

### ISSUE THREAD

**Issue by mnjenda** [MrChromebox/firmware#485] opened 2023-06-20 09:26 UTC
![image](https://github.com/MrChromebox/firmware/assets/136679962/8b240330-db2b-44df-ade9-96af74f60c8a)
That’s what I get when I boot and when I go into menu usb is not a boot option maybe I messed something up upon initial flash

_Originally posted by @Wreckz91 in https://github.com/MrChromebox/firmware/issues/432#issuecomment-1593929738_

**Comment by MrChromebox** [comment] 2023-06-20 15:14
dupe of #432

**Closed as completed by MrChromebox** 2023-06-20 15:14 UTC

**Comment by MrChromebox** [comment] 2023-07-21 19:34
this should be fixed (for reals) in the just-dropped 4.20.1 release

**Comment by haseebspaal** [comment] 2023-07-22 12:09
I faced this issue , and i have a solution to install windows now
