### ISSUE TITLE
Could unsupported devices be supported in the future?

### ISSUE THREAD

**Issue by techboyg5** [MrChromebox/firmware#247] opened 2021-01-20 13:36 UTC
This issue is just a link to [this issue](https://github.com/MrChromebox/scripts/issues/144).

* Do not comment on this issue, comment on the linked issue.
* Do not close this issue, unless the linked issue is also closed, then you can close this issue.

**Comment by MrChromebox** [comment] 2021-01-20 18:12
duplicate of #155, closing

**Closed by MrChromebox** 2021-01-20 18:12 UTC
