### ISSUE TITLE
ZAICOM

### ISSUE THREAD

**Issue by zaicomtech** [MrChromebox/firmware#372] opened 2022-08-03 05:24 UTC
lenovo x131e chromebook instal windows eror BSOD STOP ACPI BIOS EROR

**Comment by MrChromebox** [comment] 2022-08-03 14:00
duplicate of #371

**Closed as completed by MrChromebox** 2022-08-03 14:00 UTC

**Comment by zaicomtech** [comment] 2022-08-05 07:24
please solve mr chromebox what can i do with this problem BSOD stop acpi bios error

**Comment by MrChromebox** [comment] 2022-08-05 13:01
a fixed build was pushed yesterday, update and try that
