### ISSUE TITLE
a weird cpu observation...

### ISSUE THREAD

**Issue by thebestofall007** [MrChromebox/firmware#538] opened 2023-11-03 19:59 UTC
Hello, Thanks for your work. Anywho, I noticed a strange issue with the newest firmware with an hp barla chromebook with the stoneyridge processor where the CPU is throttled to about 700 mhz when I turn the chromebook on with the power button, but the CPU is at normal speed when I turn the chromebook on by opening the lid. Weird...

I'm still looking into this issue and I'll update this when I see anything else.

**Comment by MrChromebox** [comment] 2023-11-03 20:41
dupe of #530 I'm guessing

**Closed as completed by MrChromebox** 2023-11-03 20:41 UTC
