### ISSUE TITLE
HDMI Audio does not work properly on OS X.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#5] opened 2016-09-03 00:59 UTC
HDMI Audio is broken on HSW/BDW on both Windows and OS X. On Windows, CS has found a workaround using a third party program to get the EDID data and then use that to start HDMI audio. This has to be done on a per-display basis.

https://www.reddit.com/r/chrultrabook/comments/4j42ln/tutorial_enable_hdmi_audio_in_windows_no_linux/

Thanks!

**Comment by coolstar** [comment] 2016-11-16 21:28
Fixed via IGD OpRegion for Ivy Bridge and Haswell.

Broadwell has a different "chipmunk" issue.

**Comment by MrChromebox** [comment] 2016-11-16 21:32
edited title to reflect working state of HDMI audio under Windows as of 11/16 UEFI firmware release

**Comment by ReddestDream** [comment] 2016-11-16 22:28
I'll test soon on OS X to see if it has been fixed as well.

**Comment by ReddestDream** [comment] 2016-11-17 15:34
Confirmed. Still broken on OS X. HSW and BDW.

**Comment by coolstar** [comment] 2017-01-24 05:20
This is a non-issue in the firmware. HDMI audio in macOS doesn't work on my non-chromebook Lenovo Flex 3 hackintosh either (Intel HD 520 with Phoenix UEFI firmware). macOS just needs extra configuration and possibly patches.

**Comment by ReddestDream** [comment] 2017-01-24 16:25
If we can find a way to make it work w/o any changes to the firmware, and there's nothing to be gained by adding anything to the firmware (too OS X specific, as with the graphics, and makes more sense in an SSDT), then I will gladly close this issue.

**Comment by xjbhenry** [comment] 2020-05-18 01:09
@ReddestDream I recently figured out the reason. Basically pci device `8086:160c` was not named as `HDAU` in DSDT. So I named that device as HDAU and HDMI audio works now.
You can use this dsdt with AppleALC.
https://github.com/xjbhenry/asus-chromebox-cn62-hackintosh/blob/master/ACPI/dsl/SSDT-HDAU.dsl

**Comment by ReddestDream** [comment] 2020-05-18 01:11
@xjbhenry The fix was not that simple originally. Tho it is good to know that maybe AppleALC fixes this problem now . . .

**Comment by xjbhenry** [comment] 2020-05-18 01:17
@coolstar I think we need to add `HDAU` in SSDT.

**Comment by xjbhenry** [comment] 2020-05-18 01:20
> @xjbhenry The fix was not that simple originally. Tho it is good to know that maybe AppleALC fixes this problem now . . .

@ReddestDream Yes, AppleALC can add `hda-gfx` and `layout-id` for you, and make these values consistent between `HDEF` and `HDAU`. So you don't need to manually set them.

**Comment by coolstar** [comment] 2020-05-18 02:06
Oh lol I forgot about this issue, but yes I can confirm.

I’ve been using OpenCore to add HDAU via SSDT for an eternity and had HDMI audio working in macOS on my C720, but I forgot about it lol

**Comment by ReddestDream** [comment] 2020-05-18 02:07
Guess we can close this then?

**Comment by coolstar** [comment] 2020-05-18 02:08
Well might be a good idea to add HDAU to Coreboot's ACPI tables

**Comment by ReddestDream** [comment] 2020-05-18 02:08
Ah. Maybe . . .

**Comment by MrChromebox** [comment] 2020-05-18 03:40
> Well might be a good idea to add HDAU to Coreboot's ACPI tables

for what device(s)? There's maybe 1-2 that can run MacOS passably? and if one can work around it in OpenCore, same as one would on a normal PC, then I'm not sure how much of an issue this is

**Comment by coolstar** [comment] 2020-05-18 04:02
Coreboot could have the HDAU for HSW/BDW devices with the ADR set. Then the
opencore SSDT only needs to add the DSM rather than the entire device (or
clover can add the macOS properties without SSDT with HDAU added)

**Comment by xjbhenry** [comment] 2020-05-18 05:52
For Asus Chromebox 2 (CN62) GUADO, I think potentially we could add HDAU for all Haswell/Broadwell

**Comment by MrChromebox** [comment] 2020-05-18 15:58
> Coreboot could have the HDAU for HSW/BDW devices with the ADR set. 

sure, I can do that. Just need the snippet and where to add it

**Comment by coolstar** [comment] 2020-05-18 20:59
Something like this could work

```
Device (HDAU)
        {
            Name (_ADR, 0x00030000)  // _ADR: Address
        }
```

Could probably add it to src/northbridge/intel/haswell/acpi/haswell.asl and src/soc/intel/broadwell/acpi/systemagent.asl underneath the include for drivers/intel/gma/acpi/pch.asl

(Don't stick it in drivers/intel/gma/acpi/ though because Skylake+ does not have a separate HDAU device. They run HDMI audio through the normal HDEF as a 2nd codec)

**Comment by MrChromebox** [comment] 2020-05-19 04:43
done

**Comment by MrChromebox** [comment] 2020-06-07 18:15
confirmed working in 4.12 release; closing

**Closed as completed by MrChromebox** 2020-06-07 18:15 UTC
