### ISSUE TITLE
HP Chromebook 14 (Falco) switching on when connected to AC power supply

### ISSUE THREAD

**Issue by malomehi** [MrChromebox/firmware#61] opened 2017-04-14 10:55 UTC
I have an HP Falco chromebook with latest UEFI firmware installed (2017.04.09).
When the laptop is off and I connect it to the power supply it automatically turns on (even if the lid is down).
This is an issue if I just want to connect the power supply to charge the battery as I have to wait for the laptop to switch on to manually switch it off again.
Could you please look into this?
Thank you very much in advance.

**Comment by ReddestDream** [comment] 2017-04-14 18:44
This is normal Chromebook behavior. It's a ~~bug~~ feature.

Chromebooks will do this if they have been powered off for more than about an hour or so when you plug them in.

This is because, when the device is off, the Embedded Controller (EC) puts itself in a low power mode after an hour or so to save battery. Then it powers itself back on and powers the Chromebook on when you plug it back in.

This behavior, while a bit unusual for a laptop, is not unlike most phones or tablets, which will also power themselves back on if you plug them in while they are off.

It was designed this way on purpose by Google.

I hope this helps clarify things. :)

**Comment by malomehi** [comment] 2017-04-15 12:32
You have provided a perfect explanation.
Thank you.

**Comment by ReddestDream** [comment] 2017-04-15 13:32
Cool. Can you close this? Thx. :)

**Closed as completed** 2017-04-15 13:34 UTC
