### ISSUE TITLE
UEFI (Tianocore) Settings Do Not Save.

### ISSUE THREAD

**Issue by ReddestDream** [MrChromebox/firmware#10] opened 2016-09-05 23:26 UTC
The Settings in Tiano do not save. :/

This could be fixed via NVRAM or perhaps, as proposed by CoolStar, by saving them in the CMOS.

**Comment by palob** [comment] 2017-02-23 03:57
This is annoyance level 1000000.

**Comment by dalvarezsmiet** [comment] 2018-02-14 09:31
Is there any progress on this issue? It's amazing how a pain in the neck it can become...

**Comment by lis6502** [comment] 2018-07-01 20:03
Issue still exists on Lenovo x131e (chromebook Stout), settings for EFI are not saved desptie of 'commiting' changes.

**Comment by MrChromebox** [comment] 2018-07-01 21:26
@lis6502 the issue is open, it still exists on every device with UEFI firmware.  There's no mechanism to save/retrieve settings.  It's being worked on. but is not a simple task.

**Comment by lis6502** [comment] 2018-07-01 21:46
@MrChromebox i've seen that there's Closed next to some replies in this issue, so i though it's been... closed :)
I am not hardware hacker as you, but there's upstream versions of Coreboot( not specifically in Stout version)- did you managed to check how they solved saving settings?
startup.nsh resides somewhere though- maybye it's an option?
I would not mind to workaround with saving settings directly to some /EFI/config file on selected medium and querying for this file's values when booting up- if NVram is hard to access.

**Comment by MrChromebox** [comment] 2018-07-01 22:27
@lis6502 those closed tags apply to the referenced issues in those posts -- **this** issue is listed as open at the top.  There are no firmware images built from upstream coreboot with Tianocore payload which have functional saved settings.  Saving to a file on the EFI system partition was considered, but determined not to be worth the time vs working on other higher priority issues.  Work is being done now to save to NVRAM, so hopefully we'll have something for the fall release (it won't make it into the upcoming summer one)

**Comment by MrChromebox** [comment] 2018-12-26 17:21
not going to close yet, but will be resolved in next release :)

**Comment by MrChromebox** [comment] 2018-12-31 00:46
(preliminary) NVRAM support added in 2018.12.30 release

**Closed as completed by MrChromebox** 2018-12-31 00:46 UTC
Labels: bug

**Comment by moriel5** [comment] 2019-09-16 15:09
From my tests, settings do not save on any versions since the preliminary NVRAM support has been added, at least on `gnawty`.

**Comment by MrChromebox** [comment] 2019-09-16 16:22
I just tested the 8/22 release on SWANKY, and no issues with NVRAM saving. Try clearing your NVRAM settings using the script option and see if that helps

**Comment by moriel5** [comment] 2019-09-16 17:48
Thanks, I'll try that.

**Comment by moriel5** [comment] 2019-09-16 17:59
Nope, changes are still not being saved.
I had tested by trying to change the console size, could there be an unrelated bug with it?

**Comment by MrChromebox** [comment] 2019-09-16 18:00
the bootorder is the only thing hooked up; timeout, console size, language etc are not saved

**Comment by moriel5** [comment] 2019-09-16 18:04
Ah, are there any plans for saving those as well?
Since I'd like to help translate Coreboot to hebrew.

**Comment by MrChromebox** [comment] 2019-09-16 18:06
as I mentioned in the GUI issue, the current Tianocore package being used is now deprecated, so I don't plan on doing any work to it until switching over to the newer UefiPayloadPkg. 

I'm not sure what the language support is like currently, but that's Tianocore, not coreboot.

**Comment by moriel5** [comment] 2019-09-16 18:11
Sorry for not being clear.
I had meant that that I'd like to do so upstream (which probably means in this case, `UefiPayloadPkg`), since that should also remove the burden from your shoulders.

**Comment by Venji10** [comment] 2021-01-31 18:02
Hello, I just installed coreboot with tianocore on my Thinkpad X220. It works perfectly fine but I have to select the grub efi file to boot manually everytime since I neither can save the boot order and entries in tianocore nor with efibootmgr from linux.

Do I need to enable some extra config for NVRAM support or is this not the issue I have?

**Comment by MrChromebox** [comment] 2021-01-31 18:23
> Do I need to enable some extra config for NVRAM support or is this not the issue I have?

you need `CONFIG_SMMSTORE=y` (and not SMMSTORE_V2)

**Comment by Venji10** [comment] 2021-01-31 19:39
Thank you, that fixed it!
