### ISSUE TITLE
[hatch/nightfury] Accelerometer sensors not working correctly.

### ISSUE THREAD

**Issue by mapmot** [MrChromebox/firmware#340] opened 2022-04-12 17:59 UTC
Screen orientation detection works correctly with Google firmware. With the same kernel and Mr. Chromebox full UEFI firmware, the sensor readings (/sys/bus/iio/devices/iio\:device*/in_accel_*_raw) get stuck at 32767 going from "left up"  to "normal" orientation. Looks like an overflow somewhere, but I have no idea how to debug this further.

**Comment by mapmot** [comment] 2022-04-17 10:05
I flashed back the stock firmware, and the values returned from /sys/bus/iio/devices/iio:device*/in_accel_*_raw are in the range -16382:16383. It looks like a signedness issue. Maybe the modules cros_ec_sensors and cros_ec_accel expect signed value, but the ec firmware returns unsigned value? Any help in tracking the issue further is appreciated!

**Comment by mapmot** [comment] 2022-04-27 08:29
Traced the issue to the DMI BIOS version string being changed in the MrChromebox firmware.

**Comment by MrChromebox** [comment] 2022-04-27 13:33
> Traced the issue to the DMI BIOS version string being changed in the MrChromebox firmware.

can you elaborate on that?

**Comment by mapmot** [comment] 2022-04-28 04:42
linux/drivers/platform/chrome/cros_ec_lpc.c is looking for DMI_MATCH(DMI_BIOS_VERSION, "Google_"), in case of ChromeOS, and DMI_MATCH(DMI_SYS_VENDOR, "GOOGLE"), in case of custom coreboot firmware (such as MrChromebox). Nightfury is one of the few devices that report the vendor as "Google", instead of "GOOGLE". The only other such device that I know of is caroline.

**Comment by MrChromebox** [comment] 2022-04-28 13:11
> Nightfury is one of the few devices that report the vendor as "Google", instead of "GOOGLE". The only other such device that I know of is caroline.

All Skylake/Apollolake and newer CrOS devices use 'Google' for the vendor instead of 'GOOGLE'. I would submit a patch to fix the driver quirk

**Comment by MrChromebox** [comment] 2022-04-28 21:33
well shit, I already did submit a patch for this back in January. Need to ping and see why it didn't get traction

**Comment by mapmot** [comment] 2022-04-29 11:26
Celebrated too soon. Apparently it works only on the first boot after switching from ChromeOS->MrChromebox. Any subsequent boot after switching to MrChromebox, the problem reappears. Tried switching the version string to Google_Nightfury.12672.434.0 and recompiling/reflashing MrChromebox firmware - same result. Now I am suspecting either incorrect initialization of the EC, or problems with the RW EC firmware. How do I extract ecrw form the ChromeOS firmware - flashdescriptor.bin, me.bin, and ec.RW.flat? Tried replacing ec.RW.flat with the ecro from the firmware script backup, but this caused all kinds of problems, like not resuming from sleep, in addition to not solving the problem...

**Comment by MrChromebox** [comment] 2022-04-29 14:06
> How do I extract ecrw form the ChromeOS firmware - flashdescriptor.bin, me.bin, and ec.RW.flat? 

The IFD and ME have absolutely nothing to do with the EC. Nor are they writable from a live system. DON'T TOUCH THEM

> Tried replacing ec.RW.flat with the ecro from the firmware script backup, but this caused all kinds of problems, like not resuming from sleep, in addition to not solving the problem...

no shit, it's an ancient RO version. You'd want to extract ecrw from the RW section of the stock ChromeOS firmware if you're trying to replicate what ChromeOS uses. But ChromeOS has a very different driver as well, so there's that

**Comment by mapmot** [comment] 2022-04-29 18:06
In absolutely no way is ChromeOS involved in any of this. I am using exactly the same kernel. Booted under MrChromebox/UEFI - accelerometer doesn't work properly. Booted in developer mode after restoring the backup from the MrChromebox firmware script, with the same kernel signed and dd-ed to kernel partition, same OS (Gentoo) - accelerometer works properly. How do you produce ec.RW.flat in your blobs repository?

**Comment by MrChromebox** [comment] 2022-04-29 18:31
> How do you produce ec.RW.flat in your blobs repository?

by compiling it from my forked version of the Chrome-EC repo, using the correct branch and build target for the board.

Need to know the ecrw version used by stock firmware/ChromeOS to compare to my build and see where the issue is coming from

**Comment by mapmot** [comment] 2022-05-02 05:20
This is from Google firmware with correctly working accelerometer:

RO version:    nightfury_v2.0.2849-c41de27e7
RW version:    nightfury_v2.0.2851-66ac38d381
Firmware copy: RW
Build info:    nightfury_v2.0.2851-66ac38d381 2021-06-02 09:21:23 @chromeos-ci-firmware-us-east1-d-x32-1-rbnz
Tool version:  v0.0.1-8e51ac6 2022-05-02 01:12:25 gentoo@nightfury

 ChromeOS Device Firmware Utility Script [2022-04-09] 
 (c) Mr Chromebox <mrchromebox@gmail.com> 
*********************************************************
**   Device: Samsung Galaxy Chromebook 2 (NIGHTFURY-ZSLY)
** Platform: Intel CometLake
**  Fw Type: Stock ChromeOS w/RW_LEGACY
**   Fw Ver: Google_Nightfury.12672.434.0 (05/17/2021)
**    Fw WP: Disabled
*********************************************************

**Comment by MrChromebox** [comment] 2022-05-02 16:04
there's only a handful of commits different in my branch, and none seem directly related to the accelerometer or to affect NIGHTFURY. There is one related to FIFO timestamps for the gyro, which could potentially affect it. I can revert that commit and give you a test build to try. drop me an email or msg me on the chrultrabook Discord server

**Comment by MrChromebox** [comment] 2022-05-03 20:36
resolved with 2022.05.03 UEFI update; closing

**Closed as completed by MrChromebox** 2022-05-03 20:36 UTC
