### ISSUE TITLE
Supported Linux Distro for running Firmware-util?

### ISSUE THREAD

**Issue by agnivo007** [MrChromebox/firmware#446] opened 2023-03-23 15:35 UTC
I used  MX linux live iso for running firmware utility script, but the latest release seems to throw up error regards to missing glibc versions 2.33 and 2.34 ...

What is the best/supported Linux live distro to run current version firmware utility script without any tweaking?

**Comment by MrChromebox** [comment] 2023-03-23 17:12
probably a Ubuntu 22xx live ISO, I need to figure out a good way to support diff glibc versions

**Comment by ninelore** [comment] 2023-03-24 07:28
Ive made the experience that `picutils` > 3.8.0 has Issues with flashing, but that could be fixed by now.
Besides that you can go into edit mode of the live usb's boot loader and add the kernel parameter `iomem=relaxed` to make any distro with sufficient dependency versions work (had to do that on arch)

@MrChromebox about glibc: You should select the oldest distro that you want to target and build on that one. Debian bullseye  or Ubuntu 20.04 LTS (both are on 2.31) would be my suggestion.

**Comment by MrChromebox** [comment] 2023-03-24 14:32
@ninelore the problem is both glibc and pciutils. I can build for an older glibc and there's no ABI breakage with newer ones, but pciutils does break ABI compatibility with the latest version so not much I can do there

**Comment by ninelore** [comment] 2023-03-26 03:55
@MrChromebox what do you think about shipping `pciutils <= 3.8.0` for now?

**Comment by MrChromebox** [comment] 2023-03-26 17:17
@ninelore I am - 3.7.0-6 is what I'm compiling flashrom against

**Comment by SamT888** [comment] 2023-08-20 10:02
> I used MX linux live iso for running firmware utility script, but the latest release seems to throw up error regards to missing glibc versions 2.33 and 2.34 ...
> 
> What is the best/supported Linux live distro to run current version firmware utility script without any tweaking?

FydeOS works as well

**Comment by MrChromebox** [comment] 2023-10-12 23:37
closing as this is a script issue not a firmware one

**Closed as completed by MrChromebox** 2023-10-12 23:37 UTC
