### ISSUE TITLE
Chromebook Pixel 2013 (link) headphone jack issue

### ISSUE THREAD

**Issue by elektroencefalografista** [MrChromebox/firmware#364] opened 2022-07-03 16:08 UTC
After connecting headphones through a 3.5mm headphone jack they're being correctly detected, the system volume level changes, but the audio is still being routed to internal speakers. The headphone output stays quiet. The issue persists on Cloudready, brunch, and Linux distros. I'm on the newest firmware.
I tried using the chromebook_audio=1 option, but this only makes all audio devices disappear from the volume dropdown. I also tried using different kernels (mainstream and chromebook specific) to no avail.

**Comment by MrChromebox** [comment] 2022-07-03 21:29
nothing has changed on LINK w/r/t audio in years; this sounds like a kernel/driver issue, rather than a firmware/HBA verb config one

**Comment by renr4** [comment] 2022-08-24 05:08
Check that alsamixer -> HP/Speaker Auto Detect is On

**Comment by gsstark** [comment] 2022-12-13 11:18
Fwiw I see the same behaviour. This is on a 2013 Pixel that is freshly flashed with firmware and freshly installed Chromeos Flex (aka Cloudready). Plugging in a wired headphone causes the GUI to pop up the volume level widget so it's detecting the headphones but the audio continues to actually be routed through the speakers. 

The speakers also don't respond to the volume level, they are always on full volume or mute regardless of the setting in the GUI. 

Unfortunately I don't have a linux boot available so I'm limited to the tools in Chromeos, if there's any way I can debug this.

**Comment by coolstar** [comment] 2023-06-30 10:40
Headphone issue is an issue with kernel not sending EAPD HDA verb (to node 0x10) after loading codec firmware

**Comment by MrChromebox** [comment] 2023-07-21 19:36
This was possibly fixed in the 4.20.1 release, please retest with it

**Comment by coolstar** [comment] 2023-07-23 21:40
Flashed 4.20.1 + booted Windows 10 20H2 here on Link w/ Creative SoundBlaster Recon3Di driver. Can confirm speakers and headphone jack both functional

**Closed as completed** 2023-07-23 22:45 UTC

**Comment by renr4** [comment] 2023-09-06 09:28
> Headphone issue is an issue with kernel not sending EAPD HDA verb (to node 0x10) after loading codec firmware

Is there a way I can send that verb manually somehow? Just installed Cloudready 96 and everything works perfectly except that headphone jack issue.

**Comment by drafnel** [comment] 2026-02-20 18:47
Just flashed the firmware on my Pixel 2013 (LINK) to MrChromebox-2512.2 and I'm encountering this problem.

Before:
    Stock firmware rw_legacy mode (firmware write-protect screw in place)
    Dual-boot ChromeOS and Ubuntu 24.04 on internal repartitioned SSD
    Headphone jack works correctly
      - switches between internal speakers and headphone when headphone plugged in

After:
    Firmware write-protect screw removed
    Flashed MrChromebox-2512.2
    Ubuntu 24.04 installed to internal disk (ChromeOS completely removed)
    Headphone jack not working correctly
    - when headphone is plugged in, it is recognized by Ubuntu, for example the headphones is selected as the output device in the Sound Settings, but sound still plays from the internal speakers and not from the headphones.

Doesn't seem like it could be a kernel/driver issue since I was running the exact same OS/kernel/driver before updating the firmware and the headphone jack worked correctly.

I'm happy to help debug this issue and run any tests.

**Comment by drafnel** [comment] 2026-02-24 23:58
Update: it's working after using alsamixer to enable "HP/Speaker Auto Detect".

Here are the steps:
* Run alsamixer
* Hit F6 to select sound card
* Select "HDA Intel PCH"
* Use right arrow to move to "HP/Speaker Auto Detect"
* Hit 'm' to "unmute" it i.e. enable it
* Hit Escape to exit.
* Headphone jack should work now.
* Settings are persisted after reboot.

**Comment by MrChromebox** [comment] 2026-02-25 14:05
I'll check the HDA verb settings and make sure the presence-detect flag is correctly set, it may not be

**Comment by MrChromebox** [comment] 2026-02-25 17:34
I took a look, and the problem is actually in the Linux driver for the Creative CA0132 codec. It defaults to off for auto-switching via jack, you have to enable switching via alsamixer. I can't find anything in the git history which explains why this was done.

**Comment by MrChromebox** [comment] 2026-03-01 17:55
I've submitted a patch to the Linux kernel to fix this

**Comment by drafnel** [comment] 2026-03-02 19:25
Awesome, thank you! Guess I can stop trying to track this down myself 
:-)

Here's a link to the patch for those interested:

    
***@***.***/>
