### ISSUE TITLE
Google Chromebook Pixel Link Constant High Fan

### ISSUE THREAD

**Issue by joeybetamax** [MrChromebox/firmware#394] opened 2022-09-30 20:23 UTC
After a recent 8.4.2022 firmware update performed on the Link (using the FW script, the fans on the device just constant spin up maz high always after loading the OS. In the UEFI Bios menu, the fans are low to none.

OS' booted and constant fan issue on the following:

- Brunch Rammus Build
- ChromeOS Flex
- PoP OS (latest build)

Best to downgrade or would you like for me to pull logs (if so, how so)?

**Comment by MrChromebox** [comment] 2022-09-30 22:53
sounds like a bug with the cros-ec driver. The firmware just sets the fan to auto, but the OS can override via the EC interface. You can set it to manual control using google's ectool but maybe try blacklisting the ec driver first just to confirm that's the issue

**Comment by MrChromebox** [comment] 2023-05-10 15:10
closing as I can't reproduce this on LINK using the 4.19 or upcoming 4.20 firmware

**Closed as completed by MrChromebox** 2023-05-10 15:10 UTC
